version: "3.4"

services: 
  portainer:
    image: portainer/portainer
    container_name: portainer
    hostname: portainer
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
      - cert-handler_certbot-letsencrypt:/etc/letsencrypt
    command:
      --ssl
      --sslcert /etc/letsencrypt/live/www.msia17conferences.com/cert.pem
      --sslkey /etc/letsencrypt/live/www.msia17conferences.com/privkey.pem

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    hostname: jenkins
    restart: always
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment: 
      - JENKINS_OPTS="--prefix=/jenkins"

volumes:
  cert-handler_certbot-letsencrypt:
    external: true
  portainer_data:
    name: portainer_data
  jenkins_data:
    name: jenkins_data

networks: 
  default:
    external:
      name: the_network