version: "3.4"

services: 
  portainer:
    image: portainer/portainer
    container_name: portainer
    hostname: portainer
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
      - cert-handler_certbot-letsencrypt:/etc/letsencrypt
    command:
      --ssl
      --sslcert /etc/letsencrypt/live/www.msia17conferences.com/cert.pem
      --sslkey /etc/letsencrypt/live/www.msia17conferences.com/privkey.pem

  jenkins:
    # image: jenkins/jenkins:lts
    build: ./jenkins
    container_name: jenkins
    hostname: jenkins
    restart: always
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment: 
      - JENKINS_OPTS="--prefix=/jenkins"

  # jks_docker_slave:
  #   image: jenkins/ssh-slave 
  #   container_name: jks_docker_slave
  #   hostname: jks_docker_slave
  #   command: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC49TDHrMu7I5aOz4eJ2uHoIr3zyqC49rQYn9ALAKBTSPlWXCkhAE2c4qomUdYPObx7KhTc0Rj9sVU4fm0yBT6kenl+24Edoe1GvnKoijdjy+7CiLb9n4BkS1Q8cNrIKkG0djLdYmEsPyois6bad5Tv4EkOVYluTJQhx1rmlOPfgj9xcq0EHgigoEHRRNt69t0YV8NtgKqSz0XDt02YdBoBaCV3wVcc7vJXzdWSORp4EBArDkdh1rCDVSuz6gHThBAgc+mkJZL//lAbufUwldwhYeEDoQXl5UFv0qp28WJVlfafS5WiRiuctetDS2U4Flp2FqqkPjJV2cpuJqgK5n4t neito@instance-template-1"

  sonarqube:
    image: sonarqube:lts
    container_name: sonarqube
    hostname: sonarqube
    restart: always
    ports:
      - 9000:9000
    environment:
      - sonar.jdbc.username=sonar
      - sonar.jdbc.password=sonar
      - sonar.jdbc.url=jdbc:postgresql://postgres:5432/sonar
      - sonar.web.context=/sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/

  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    container_name: postgres
    hostname: postgres
    restart: always
    ports:
      - 5432:5432
    env_file: ./postgres/pg-env.list
    volumes:
      - postgres_data:/var/lib/postgresql

  pg_admin:
    image: dpage/pgadmin4:latest
    container_name: pg_admin
    hostname: pg_admin
    restart: always
    ports: 
      - 9001:80
    env_file: ./pgadmin/pgadmin-env.list 
    volumes: 
      - pgadmin_data:/var/lib/pgadmin

  minio: 
    image: minio/minio
    container_name: minio
    hostname: minio
    restart: always
    ports: 
      - 9000
    env_file: ./minio/minio-env.list
    volumes:
      - /var/minio:/data
    command: server /data

  mongodb:
    image: mongo:4.2
    container_name: mongodb
    hostname : mongodb
    restart: always
    ports:
      - 27017
    volumes:
      - mongodb_data:/data/db
      
  mqtt_server:
    container_name: mqtt_server
    hostname: mqtt_server
    image: eclipse-mosquitto:1.6.7
    restart: always
    ports:
      - 1883
      - 9001
    volumes: 
      - mqtt_data:/mosquitto/data
      - mqtt_log:/mosquitto/log
      - ./mqtt/config:/mosquitto/config
      - cert-handler_certbot-letsencrypt:/etc/letsencrypt

volumes:
  cert-handler_certbot-letsencrypt:
    external: true
  portainer_data:
    name: portainer_data
  jenkins_data:
    name: jenkins_data
  sonarqube_data:
    name: sonarqube_data
  postgres_data:
    name: postgres_data
  pgadmin_data:
    name: pgadmin_data
  mongodb_data:
    name: mongodb_data
  mqtt_data:
    name: mqtt_data
  mqtt_log:
    name: mqtt_log

networks: 
  default:
    external:
      name: the_network