FROM postgres:10.10-alpine

ENV PG_PRIMARY_USER=postgres
ENV PG_PRIMARY_PASSWORD=admin
ENV PG_ROOT_PASSWORD=admin
ENV PG_USER=admin
ENV PG_PASSWORD=admin
ENV PG_DATABASE=default
ENV PG_PRIMARY_PORT=5432

ADD ./setup_postgres.sh /tmp/setup_postgres.sh